
/**
 * Write a description of class CLI here.
 * 
 * @author (your name) 
 * @version (a version number or a date)
 */

import java.util.Scanner;


public class CLI
{
    static Bot currentbot;
    public static String debugLog = "";
    static boolean debug = false;
    
    public static void main(String args[]){
        
        FileHandler fileHandler = new FileHandler();
        
        Scanner user_input = new Scanner( System.in );
        String input = "";
        printCommands();
        while(!input.equals("-e")){
            try{
                System.out.print(" >>  ");
                input = user_input.next();
                if(input.equals("-n")){
                    input = user_input.next();
                    currentbot = new Bot(input);
                    System.out.println("New bot " + input + " created");
                }
                else if(input.equals("-rnl")){
                    input = user_input.next();
                    currentbot.readAndLearn(input);
                }
                else if(input.equals("-l")){
                    input = user_input.next();
                    currentbot = fileHandler.loadABot(input);
                }
                else if(input.equals("-aluw")){
                    currentbot.teachBadLastWords();
                }
                else if(input.equals("-h")){
                    printCommands();
                }
                else if(input.equals("-s")){
                    fileHandler.saveABot(currentbot);
                } 
                else if(input.equals("-t")){
                    input = user_input.next();
                    currentbot.teachText( input );
                }
                else if(input.equals("-d")){
                    currentbot.dump();
                }
                else if(input.equals("-debug")){
                    if(debug){
                        debug = false;
                    } else {
                        debug = true;
                    }
                }
                else if(input.equals("-f")){
                    input = user_input.next();
                    if(input.equals("y")){
                        currentbot.learnFromLastDecision(true);
                    } else if (input.equals("n")){
                         currentbot.learnFromLastDecision(false);
                    } else {
                        System.out.println("bad value");
                    }
                }
                else if(input.equals("-r")){
                    input = user_input.next();
                    currentbot.readText(input);
                }
                else if(input.equals("-guw")){
                    input = user_input.next();
                    String f2 = user_input.next();
                    String f3 = user_input.next();
                    currentbot.compareAndRemove(input, f2, f3);
                } 
                
                else if(input.equals("-e")){} else {
                    debugLog += "command not recognised";
                }
                
            
            } catch (Exception e) {
                System.out.println("something didn't work "); 
                e.printStackTrace();
            }
            
            if(debug){
                System.out.println(debugLog);
            }
            debugLog = "";
        }
    }
    
    public static void printCommands(){
        System.out.println("Commands:");
        System.out.println("    -h               print commands help list\n");
        System.out.println("    -l <file name>   load a previously saved bot\n");
        System.out.println("    -n <bot name>    create a new bot\n");
        System.out.println("    -s               save a bot\n");
        System.out.println("    -rnl <file name> the bot reads a text and learns it if it likes it\n");
        System.out.println("    -r <file name>   the bot reads and analyses a text\n");
        System.out.println("    -t <file name>   the bot is taught from a text\n");
        System.out.println("    -f <y/n>         feedback: Should the bot have liked the last text"); 
        System.out.println("                     it has read or not?\n");
        System.out.println("    -aluw            the word matches from the last text read are added"); 
        System.out.println("                     to the useless words list\n");
        System.out.println("    -guw <f1 f2 f3>  the bot specific useless words list is generated by");
        System.out.println("                     comparing common words of three texts\n");
        System.out.println("    -d               dump the contents of the bot's perceptrons\n");
        System.out.println("    -debug           turn debugging on/off\n");
        System.out.println("    -chwer <float>   change the error margine for the words\n");
        System.out.println("    -chwger <float>  change the error margine for the group of words\n");
        System.out.println("    -e               exit the app\n");
    }
}
